Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from mtbp3.health import ectd
ctoc = ectd.ctoc_by_fda(ectd_version='3.2.2', ctoc_version='2.3.3')
print('\n'.join(ctoc.show_ctoc_tree(1)))

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmtbp3[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhealth[39;00m [38;5;28;01mimport[39;00m ectd
[0;32m----> 2[0m ctoc [38;5;241m=[39m [43mectd[49m[38;5;241;43m.[39;49m[43mctoc_by_fda[49m[43m([49m[43mectd_version[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m3.2.2[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mctoc_version[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m2.3.3[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m[38;5;241m.[39mjoin(ctoc[38;5;241m.[39mshow_ctoc_tree([38;5;241m1[39m)))

File [0;32m~/work/mtbp3/mtbp3/mtbp3/health/ectd.py:28[0m, in [0;36mctoc_by_fda.__init__[0;34m(self, ectd_version, ctoc_version)[0m
[1;32m     26[0m [38;5;28mself[39m[38;5;241m.[39mctoc_version [38;5;241m=[39m ctoc_version
[1;32m     27[0m [38;5;28mself[39m[38;5;241m.[39mfolder_name [38;5;241m=[39m mtbp3[38;5;241m.[39mget_data([38;5;124mf[39m[38;5;124m'[39m[38;5;124msupp_ectd/fda_ectd[39m[38;5;132;01m{[39;00mectd_version[38;5;132;01m}[39;00m[38;5;124m_ctocv[39m[38;5;132;01m{[39;00mctoc_version[38;5;132;01m}[39;00m[38;5;124m.txt[39m[38;5;124m'[39m)
[0;32m---> 28[0m [38;5;28mself[39m[38;5;241m.[39mctoc [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__load_list[49m[43m([49m[43m)[49m

File [0;32m~/work/mtbp3/mtbp3/mtbp3/health/ectd.py:39[0m, in [0;36mctoc_by_fda.__load_list[0;34m(self)[0m
[1;32m     37[0m     [38;5;28;01mreturn[39;00m lines
[1;32m     38[0m [38;5;28;01melse[39;00m:
[0;32m---> 39[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mVersion [39m[38;5;132;01m{[39;00m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mversion[49m[38;5;132;01m}[39;00m[38;5;124m not found.[39m[38;5;124m"[39m)
[1;32m     40[0m     [38;5;28;01mreturn[39;00m []

[0;31mAttributeError[0m: 'ctoc_by_fda' object has no attribute 'version'

