Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pt_list = emt.find_fmq(fmq=fmq_list[0], narrow_only=False)
print(pt_list['classification'].value_counts())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m pt_list [38;5;241m=[39m [43memt[49m[38;5;241;43m.[39;49m[43mfind_fmq[49m[43m([49m[43mfmq[49m[38;5;241;43m=[39;49m[43mfmq_list[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[43mnarrow_only[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[1;32m      2[0m [38;5;28mprint[39m(pt_list[[38;5;124m'[39m[38;5;124mclassification[39m[38;5;124m'[39m][38;5;241m.[39mvalue_counts())

File [0;32m~/work/mtbp3/mtbp3/mtbp3/util/emt.py:684[0m, in [0;36mEmt.find_fmq[0;34m(self, fmq, narrow_only)[0m
[1;32m    682[0m     [38;5;28;01mreturn[39;00m [38;5;28mlist[39m([38;5;28mself[39m[38;5;241m.[39mfmq_list[[38;5;124m'[39m[38;5;124mfmq[39m[38;5;124m'[39m][38;5;241m.[39munique())
[1;32m    683[0m [38;5;28;01melse[39;00m:
[0;32m--> 684[0m     [38;5;28;01massert[39;00m [38;5;28misinstance[39m(fmq, [38;5;28mlist[39m), [38;5;124m"[39m[38;5;124mfmq should be a list[39m[38;5;124m"[39m
[1;32m    685[0m     [38;5;28;01mif[39;00m narrow_only:
[1;32m    686[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mfmq_list[([38;5;28mself[39m[38;5;241m.[39mfmq_list[[38;5;124m'[39m[38;5;124mfmq[39m[38;5;124m'[39m][38;5;241m.[39misin(fmq)) [38;5;241m&[39m ([38;5;28mself[39m[38;5;241m.[39mfmq_list[[38;5;124m'[39m[38;5;124mclassification[39m[38;5;124m'[39m] [38;5;241m==[39m [38;5;124m'[39m[38;5;124mNarrow[39m[38;5;124m'[39m)][[[38;5;124m'[39m[38;5;124mfmq[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mpt[39m[38;5;124m'[39m]]

[0;31mAssertionError[0m: fmq should be a list

