Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('\n'.join(emt.show_fmq_tree(fmq_list[:2], with_soc=True)))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m[38;5;241m.[39mjoin([43memt[49m[38;5;241;43m.[39;49m[43mshow_fmq_tree[49m[43m([49m[43mfmq_list[49m[43m[[49m[43m:[49m[38;5;241;43m2[39;49m[43m][49m[43m,[49m[43m [49m[43mwith_soc[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m))

File [0;32m~/work/mtbp3/mtbp3/mtbp3/health/emt.py:762[0m, in [0;36mEmt.show_fmq_tree[0;34m(self, fmq, with_soc, ignore_case, to_right)[0m
[1;32m    760[0m     lists [38;5;241m=[39m pt_df[[38;5;124m'[39m[38;5;124mfmq_class_soc[39m[38;5;124m'[39m][38;5;241m.[39munique()[38;5;241m.[39mtolist()
[1;32m    761[0m     list2 [38;5;241m=[39m pt_df[[38;5;124m'[39m[38;5;124mfmq_class_soc_pt[39m[38;5;124m'[39m][38;5;241m.[39munique()[38;5;241m.[39mtolist()
[0;32m--> 762[0m     [38;5;28;01mreturn[39;00m [43mmtbp3[49m[38;5;241;43m.[39;49m[43mutil[49m[38;5;241;43m.[39;49m[43mcdt[49m[38;5;241;43m.[39;49m[43mlist_tree[49m(lst [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mFMQ/[39m[38;5;124m'[39m][38;5;241m+[39mlist0[38;5;241m+[39mlist1[38;5;241m+[39mlists[38;5;241m+[39mlist2, to_right[38;5;241m=[39mto_right)
[1;32m    763[0m [38;5;28;01melse[39;00m:
[1;32m    764[0m     pt_df [38;5;241m=[39m pt_df[38;5;241m.[39msort_values(by[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mfmq[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mclassification[39m[38;5;124m'[39m])

[0;31mAttributeError[0m: module 'mtbp3.util.cdt' has no attribute 'list_tree'

