Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from mtbp3.health import ectd
ctoc = ectd.ctoc_by_fda()
print('\n'.join(ctoc.show_ctoc_tree(1)))

------------------

----- stdout -----
Version 2.3.3 not found.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmtbp3[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhealth[39;00m [38;5;28;01mimport[39;00m ectd
[1;32m      2[0m ctoc [38;5;241m=[39m ectd[38;5;241m.[39mctoc_by_fda()
[0;32m----> 3[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m[38;5;241m.[39mjoin([43mctoc[49m[38;5;241;43m.[39;49m[43mshow_ctoc_tree[49m[43m([49m[38;5;241;43m1[39;49m[43m)[49m))

File [0;32m~/work/mtbp3/mtbp3/mtbp3/health/ectd.py:43[0m, in [0;36mctoc_by_fda.show_ctoc_tree[0;34m(self, module, to_right)[0m
[1;32m     40[0m     module [38;5;241m=[39m [38;5;241m1[39m
[1;32m     42[0m filtered_ctoc [38;5;241m=[39m [item [38;5;28;01mfor[39;00m item [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mctoc [38;5;28;01mif[39;00m item[38;5;241m.[39mstartswith([38;5;28mstr[39m(module))]
[0;32m---> 43[0m tree [38;5;241m=[39m [43mListTree[49m[43m([49m[43mlst[49m[38;5;241;43m=[39;49m[43mfiltered_ctoc[49m[43m,[49m[43m [49m[43minfmt[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mdotspace[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     44[0m [38;5;28;01mreturn[39;00m tree[38;5;241m.[39mlist_tree(to_right[38;5;241m=[39mto_right)

[0;31mTypeError[0m: ListTree.__init__() got an unexpected keyword argument 'infmt'

