Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('\n'.join(emt.show_fmq_tree(fmq_list[:2])))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m[38;5;241m.[39mjoin([43memt[49m[38;5;241;43m.[39;49m[43mshow_fmq_tree[49m[43m([49m[43mfmq_list[49m[43m[[49m[43m:[49m[38;5;241;43m2[39;49m[43m][49m[43m)[49m))

File [0;32m~/work/mtbp3/mtbp3/mtbp3/health/emt.py:779[0m, in [0;36mEmt.show_fmq_tree[0;34m(self, fmq, with_soc, ignore_case, to_right)[0m
[1;32m    777[0m list1 [38;5;241m=[39m pt_df[[38;5;124m'[39m[38;5;124mfmq_class[39m[38;5;124m'[39m][38;5;241m.[39munique()[38;5;241m.[39mtolist()
[1;32m    778[0m list2 [38;5;241m=[39m pt_df[[38;5;124m'[39m[38;5;124mfmq_class_pt[39m[38;5;124m'[39m][38;5;241m.[39munique()[38;5;241m.[39mtolist()
[0;32m--> 779[0m tree [38;5;241m=[39m [43mutil[49m[38;5;241;43m.[39;49m[43mlsr[49m[38;5;241;43m.[39;49m[43mListTree[49m(lst [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mFMQ/[39m[38;5;124m'[39m][38;5;241m+[39mlist0[38;5;241m+[39mlist1[38;5;241m+[39mlist2)
[1;32m    780[0m [38;5;28;01mreturn[39;00m tree[38;5;241m.[39mlist_tree(to_right[38;5;241m=[39mto_right)

[0;31mAttributeError[0m: module 'mtbp3.util.lsr' has no attribute 'ListTree'

